name: mdi
description: Some widgets playground based on a desktop like UI.
version: 0.0.11

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  webview_flutter_web: ^0.2.3+4

  webview_flutter_platform_interface: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  assets:
    - google_fonts/
    - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: google_fonts/Roboto-Regular.ttf
  uses-material-design: true
